import 'package:phosphor_icons/phosphor_icons.dart';

import '../models/food_guide.dart';
import 'app_icons.dart';

/// 영양 가이드 고정 데이터 (앱에 포함). 수치는 1회 분량 기준 참고용 대략값이며
/// 조리법·제품에 따라 달라진다. 정밀값(식약처 식품영양성분 DB)은 후속 작업.
class FoodGuideData {
  FoodGuideData._();

  static const _c = FoodTag.convenience;
  static const _n = FoodTag.noCook;
  static const _p = FoodTag.plant;

  static const List<NutrientCategoryInfo> categories = [
    NutrientCategoryInfo(
      category: NutrientCategory.protein,
      icon: PhosphorIconsRegular.egg,
      tagline: '근육 회복',
      description: '근육 회복에 필요해요. 끼니마다 손바닥 크기 한 덩이가 기준이에요.',
    ),
    NutrientCategoryInfo(
      category: NutrientCategory.carb,
      icon: PhosphorIconsRegular.grains,
      tagline: '운동 에너지',
      description: '운동할 힘을 내요. 끼니마다 주먹 하나 크기가 기준이에요.',
    ),
    NutrientCategoryInfo(
      category: NutrientCategory.fat,
      icon: PhosphorIconsRegular.avocado,
      tagline: '포만감 · 호르몬',
      description: '포만감과 호르몬에 필요해요. 끼니마다 엄지 한 마디 정도면 충분해요.',
    ),
    NutrientCategoryInfo(
      category: NutrientCategory.vegFruit,
      icon: PhosphorIconsRegular.carrot,
      tagline: '비타민 · 식이섬유',
      description: '비타민과 식이섬유를 채워요. 끼니마다 두 주먹 정도 곁들이세요.',
    ),
  ];

  static const List<FoodSituation> situations = [
    FoodSituation(
      id: 'pre_workout',
      title: '운동 1–2시간 전',
      icon: PhosphorIconsRegular.lightning,
      description: '소화가 잘 되는 탄수화물 위주로 먹고, 기름진 음식은 피하세요.',
      foodIds: [
        'banana',
        'sweet_potato',
        'whole_wheat_bread',
        'peanut_butter',
        'oatmeal',
        'greek_yogurt',
        'bagel',
      ],
    ),
    FoodSituation(
      id: 'post_workout',
      title: '운동 직후',
      icon: AppIcons.workout,
      description: '운동 후 1–2시간 안에 단백질과 탄수화물을 함께 먹으면 회복에 좋아요.',
      foodIds: [
        'chicken_breast',
        'brown_rice',
        'milk',
        'protein_drink',
        'egg',
        'banana',
        'tuna_can',
        'white_rice',
      ],
    ),
    FoodSituation(
      id: 'late_night',
      title: '저녁 · 야식이 당길 때',
      icon: PhosphorIconsRegular.moon,
      description: '단백질이 많고 가벼운 음식으로, 양은 손바닥 하나만큼만 드세요.',
      foodIds: [
        'greek_yogurt',
        'egg',
        'tofu',
        'soy_milk',
        'cherry_tomato',
        'cucumber',
        'cheese',
      ],
    ),
    FoodSituation(
      id: 'convenience',
      title: '편의점 · 외식할 때',
      icon: PhosphorIconsRegular.storefront,
      description: '단백질 하나 + 탄수화물 하나 + 채소 하나로 골라 보세요.',
      foodIds: [
        'chicken_breast',
        'egg',
        'gimbap_half',
        'salad_pack',
        'protein_drink',
        'greek_yogurt',
        'sweet_potato',
        'nuts_pack',
        'milk',
        'cherry_tomato',
      ],
    ),
  ];

  static const List<FoodItem> foods = [
    // ── 단백질 ──
    FoodItem(
      id: 'chicken_breast',
      name: '닭가슴살',
      category: NutrientCategory.protein,
      serving: '100g',
      kcal: 109,
      protein: 23,
      carbs: 0,
      fat: 1.2,
      tags: {_c},
      howToEat: ['삶거나 구워서 샐러드·밥과 함께', '편의점 훈제 제품도 괜찮아요 (나트륨은 확인)'],
      pairsWith: ['brown_rice', 'sweet_potato', 'broccoli'],
    ),
    FoodItem(
      id: 'egg',
      name: '삶은 계란',
      category: NutrientCategory.protein,
      serving: '1개',
      kcal: 72,
      protein: 6.3,
      carbs: 0.4,
      fat: 4.8,
      tags: {_c, _n},
      howToEat: ['2개면 단백질 12g 정도예요', '노른자까지 먹어도 괜찮아요'],
      pairsWith: ['whole_wheat_bread', 'cherry_tomato', 'salad_pack'],
    ),
    FoodItem(
      id: 'mackerel',
      name: '고등어',
      category: NutrientCategory.protein,
      serving: '1토막 100g',
      kcal: 205,
      protein: 20,
      carbs: 0,
      fat: 13,
      howToEat: ['구이나 조림으로', '오메가-3 지방도 함께 채워요'],
      pairsWith: ['brown_rice', 'spinach', 'cabbage'],
    ),
    FoodItem(
      id: 'greek_yogurt',
      name: '그릭요거트',
      category: NutrientCategory.protein,
      serving: '1컵 100g',
      kcal: 97,
      protein: 9,
      carbs: 4,
      fat: 5,
      tags: {_c, _n},
      howToEat: ['무가당 플레인으로 고르세요', '과일·견과를 올려 한 끼로'],
      pairsWith: ['blueberry', 'banana', 'almonds'],
    ),
    FoodItem(
      id: 'tofu',
      name: '두부',
      category: NutrientCategory.protein,
      serving: '1/3모 100g',
      kcal: 84,
      protein: 9,
      carbs: 2,
      fat: 5,
      tags: {_p},
      howToEat: ['데우거나 부쳐서 반찬으로', '찌개에 넣으면 포만감이 커요'],
      pairsWith: ['brown_rice', 'spinach', 'mushroom'],
    ),
    FoodItem(
      id: 'beef_round',
      name: '소고기 우둔',
      category: NutrientCategory.protein,
      serving: '100g',
      kcal: 130,
      protein: 22,
      carbs: 0,
      fat: 4.5,
      howToEat: ['기름기 적은 부위라 구이·장조림에 좋아요', '철분도 함께 채워요'],
      pairsWith: ['white_rice', 'mushroom', 'cabbage'],
    ),
    FoodItem(
      id: 'milk',
      name: '우유',
      category: NutrientCategory.protein,
      serving: '1잔 200ml',
      kcal: 130,
      protein: 6,
      carbs: 9.5,
      fat: 7.6,
      tags: {_c, _n},
      howToEat: ['운동 직후 한 잔이면 간단해요', '배가 불편하면 락토프리 우유로'],
      pairsWith: ['banana', 'oatmeal', 'whole_wheat_bread'],
    ),
    FoodItem(
      id: 'tuna_can',
      name: '참치캔',
      category: NutrientCategory.protein,
      serving: '1캔 100g (기름 뺀)',
      kcal: 120,
      protein: 24,
      carbs: 0,
      fat: 2,
      tags: {_c, _n},
      howToEat: ['기름을 따라 버리고 드세요', '밥이나 샐러드에 올려서'],
      pairsWith: ['white_rice', 'salad_pack', 'cucumber'],
    ),
    FoodItem(
      id: 'pork_tenderloin',
      name: '돼지 안심',
      category: NutrientCategory.protein,
      serving: '100g',
      kcal: 120,
      protein: 22,
      carbs: 0,
      fat: 3.5,
      howToEat: ['수육이나 구이로', '기름기 적은 부위예요'],
      pairsWith: ['cabbage', 'brown_rice', 'mushroom'],
    ),
    FoodItem(
      id: 'protein_drink',
      name: '프로틴 음료',
      category: NutrientCategory.protein,
      serving: '1병 250ml',
      kcal: 110,
      protein: 20,
      carbs: 5,
      fat: 1.5,
      tags: {_c, _n},
      howToEat: ['끼니를 거른 날이나 운동 직후에', '당류가 적은 제품을 고르세요'],
      pairsWith: ['banana', 'sweet_potato', 'gimbap_half'],
    ),
    FoodItem(
      id: 'shrimp',
      name: '새우',
      category: NutrientCategory.protein,
      serving: '100g',
      kcal: 95,
      protein: 20,
      carbs: 0,
      fat: 1,
      howToEat: ['데치거나 볶아서', '냉동 새우를 두면 편해요'],
      pairsWith: ['broccoli', 'brown_rice', 'avocado'],
    ),
    FoodItem(
      id: 'soy_milk',
      name: '무가당 두유',
      category: NutrientCategory.protein,
      serving: '1팩 190ml',
      kcal: 90,
      protein: 7,
      carbs: 4,
      fat: 5,
      tags: {_c, _n, _p},
      howToEat: ['우유 대신 마시기 좋아요', '가당 제품은 당류를 확인하세요'],
      pairsWith: ['oatmeal', 'banana', 'whole_wheat_bread'],
    ),

    // ── 탄수화물 ──
    FoodItem(
      id: 'brown_rice',
      name: '현미밥',
      category: NutrientCategory.carb,
      serving: '1공기 200g',
      kcal: 300,
      protein: 6,
      carbs: 64,
      fat: 2,
      tags: {_c},
      howToEat: ['흰쌀밥보다 천천히 소화돼요', '즉석밥 제품도 있어요'],
      pairsWith: ['chicken_breast', 'tofu', 'mackerel'],
    ),
    FoodItem(
      id: 'white_rice',
      name: '흰쌀밥',
      category: NutrientCategory.carb,
      serving: '1공기 210g',
      kcal: 315,
      protein: 5.5,
      carbs: 70,
      fat: 0.6,
      tags: {_c},
      howToEat: ['운동 직후 빠른 에너지 보충에 좋아요', '양은 한 공기를 넘기지 않게'],
      pairsWith: ['beef_round', 'tuna_can', 'spinach'],
    ),
    FoodItem(
      id: 'sweet_potato',
      name: '고구마',
      category: NutrientCategory.carb,
      serving: '1개 150g',
      kcal: 195,
      protein: 2.3,
      carbs: 46,
      fat: 0.2,
      tags: {_c},
      howToEat: ['찌거나 구워서', '편의점 군고구마도 괜찮아요'],
      pairsWith: ['chicken_breast', 'milk', 'egg'],
    ),
    FoodItem(
      id: 'banana',
      name: '바나나',
      category: NutrientCategory.carb,
      serving: '1개 120g',
      kcal: 105,
      protein: 1.3,
      carbs: 27,
      fat: 0.4,
      tags: {_c, _n, _p},
      howToEat: ['운동 30분–1시간 전에 간단히', '들고 다니기 좋아요'],
      pairsWith: ['greek_yogurt', 'peanut_butter', 'milk'],
    ),
    FoodItem(
      id: 'oatmeal',
      name: '오트밀',
      category: NutrientCategory.carb,
      serving: '40g',
      kcal: 150,
      protein: 5,
      carbs: 27,
      fat: 2.8,
      tags: {_n, _p},
      howToEat: ['우유나 두유에 불려서', '전자레인지에 1분 데워도 돼요'],
      pairsWith: ['milk', 'blueberry', 'banana'],
    ),
    FoodItem(
      id: 'whole_wheat_bread',
      name: '통밀빵',
      category: NutrientCategory.carb,
      serving: '2쪽 60g',
      kcal: 150,
      protein: 6,
      carbs: 26,
      fat: 2,
      tags: {_c, _n, _p},
      howToEat: ['계란·땅콩버터를 곁들여 아침으로', '성분표에서 통밀 함량을 확인하세요'],
      pairsWith: ['egg', 'peanut_butter', 'avocado'],
    ),
    FoodItem(
      id: 'potato',
      name: '감자',
      category: NutrientCategory.carb,
      serving: '1개 150g',
      kcal: 105,
      protein: 2.5,
      carbs: 24,
      fat: 0.1,
      tags: {_p},
      howToEat: ['찌거나 구워서', '튀긴 감자는 피하세요'],
      pairsWith: ['chicken_breast', 'egg', 'broccoli'],
    ),
    FoodItem(
      id: 'gimbap_half',
      name: '김밥',
      category: NutrientCategory.carb,
      serving: '반 줄',
      kcal: 160,
      protein: 5,
      carbs: 27,
      fat: 4,
      tags: {_c, _n},
      howToEat: ['반 줄에 단백질 음식 하나를 더하세요', '참치·계란 김밥이 단백질이 더 많아요'],
      pairsWith: ['egg', 'protein_drink', 'milk'],
    ),
    FoodItem(
      id: 'corn',
      name: '찐 옥수수',
      category: NutrientCategory.carb,
      serving: '1개 150g',
      kcal: 140,
      protein: 4.5,
      carbs: 30,
      fat: 1.5,
      tags: {_c, _p},
      howToEat: ['간식으로 하나', '식이섬유가 많아 포만감이 오래가요'],
      pairsWith: ['milk', 'egg', 'soy_milk'],
    ),
    FoodItem(
      id: 'bagel',
      name: '플레인 베이글',
      category: NutrientCategory.carb,
      serving: '1개 100g',
      kcal: 260,
      protein: 10,
      carbs: 50,
      fat: 1.5,
      tags: {_c, _n},
      howToEat: ['운동 1–2시간 전에 반 개–한 개', '크림치즈보다 땅콩버터를 곁들이세요'],
      pairsWith: ['peanut_butter', 'egg', 'greek_yogurt'],
    ),
    FoodItem(
      id: 'kabocha',
      name: '단호박',
      category: NutrientCategory.carb,
      serving: '1/4통 200g',
      kcal: 100,
      protein: 2,
      carbs: 24,
      fat: 0.2,
      tags: {_p},
      howToEat: ['쪄서 밥 대신 먹어도 돼요', '전자레인지로 5분이면 익어요'],
      pairsWith: ['chicken_breast', 'greek_yogurt', 'egg'],
    ),
    FoodItem(
      id: 'buckwheat_noodle',
      name: '메밀국수',
      category: NutrientCategory.carb,
      serving: '1인분 200g (삶은)',
      kcal: 230,
      protein: 9,
      carbs: 48,
      fat: 1,
      tags: {_p},
      howToEat: ['국물·소스는 조금만', '계란이나 두부를 곁들이세요'],
      pairsWith: ['egg', 'tofu', 'cucumber'],
    ),

    // ── 지방 ──
    FoodItem(
      id: 'almonds',
      name: '아몬드',
      category: NutrientCategory.fat,
      serving: '20알 23g',
      kcal: 135,
      protein: 5,
      carbs: 5,
      fat: 12,
      tags: {_c, _n, _p},
      howToEat: ['간식으로 한 줌만', '무염 제품을 고르세요'],
      pairsWith: ['greek_yogurt', 'apple', 'oatmeal'],
    ),
    FoodItem(
      id: 'walnuts',
      name: '호두',
      category: NutrientCategory.fat,
      serving: '3알 15g',
      kcal: 98,
      protein: 2.3,
      carbs: 2,
      fat: 9.8,
      tags: {_n, _p},
      howToEat: ['오메가-3 지방이 많아요', '요거트·오트밀에 부숴 넣어서'],
      pairsWith: ['greek_yogurt', 'oatmeal', 'banana'],
    ),
    FoodItem(
      id: 'nuts_pack',
      name: '하루 견과',
      category: NutrientCategory.fat,
      serving: '1봉 20g',
      kcal: 120,
      protein: 4,
      carbs: 5,
      fat: 10,
      tags: {_c, _n, _p},
      howToEat: ['한 봉이 하루 적당량이에요', '초콜릿·건과일이 든 제품은 당류 확인'],
      pairsWith: ['milk', 'greek_yogurt', 'apple'],
    ),
    FoodItem(
      id: 'avocado',
      name: '아보카도',
      category: NutrientCategory.fat,
      serving: '반 개 70g',
      kcal: 112,
      protein: 1.4,
      carbs: 6,
      fat: 10,
      tags: {_n, _p},
      howToEat: ['빵이나 샐러드에 올려서', '잘 익어 살짝 말랑할 때 드세요'],
      pairsWith: ['whole_wheat_bread', 'egg', 'shrimp'],
    ),
    FoodItem(
      id: 'peanut_butter',
      name: '땅콩버터',
      category: NutrientCategory.fat,
      serving: '1큰술 16g',
      kcal: 95,
      protein: 4,
      carbs: 3,
      fat: 8,
      tags: {_n, _p},
      howToEat: ['땅콩 100% 제품을 고르세요', '한 큰술이면 충분해요'],
      pairsWith: ['banana', 'whole_wheat_bread', 'bagel'],
    ),
    FoodItem(
      id: 'olive_oil',
      name: '올리브유',
      category: NutrientCategory.fat,
      serving: '1큰술 10g',
      kcal: 88,
      protein: 0,
      carbs: 0,
      fat: 10,
      tags: {_p},
      howToEat: ['샐러드 드레싱으로', '볶음 요리 기름 대신'],
      pairsWith: ['salad_pack', 'cherry_tomato', 'broccoli'],
    ),
    FoodItem(
      id: 'salmon',
      name: '연어',
      category: NutrientCategory.fat,
      serving: '100g',
      kcal: 206,
      protein: 20,
      carbs: 0,
      fat: 13,
      howToEat: ['구이나 회로', '단백질과 오메가-3를 함께 채워요'],
      pairsWith: ['brown_rice', 'avocado', 'spinach'],
    ),
    FoodItem(
      id: 'cheese',
      name: '슬라이스 치즈',
      category: NutrientCategory.fat,
      serving: '1장 20g',
      kcal: 60,
      protein: 3.5,
      carbs: 1,
      fat: 4.8,
      tags: {_c, _n},
      howToEat: ['빵·계란에 곁들여서', '하루 1–2장이면 충분해요'],
      pairsWith: ['whole_wheat_bread', 'egg', 'cherry_tomato'],
    ),
    FoodItem(
      id: 'chia_seed',
      name: '치아씨드',
      category: NutrientCategory.fat,
      serving: '1큰술 12g',
      kcal: 58,
      protein: 2,
      carbs: 5,
      fat: 3.7,
      tags: {_n, _p},
      howToEat: ['요거트·우유에 불려서', '물을 충분히 함께 드세요'],
      pairsWith: ['greek_yogurt', 'milk', 'blueberry'],
    ),
    FoodItem(
      id: 'dark_chocolate',
      name: '다크 초콜릿',
      category: NutrientCategory.fat,
      serving: '2조각 20g',
      kcal: 110,
      protein: 1.6,
      carbs: 9,
      fat: 8,
      tags: {_c, _n},
      howToEat: ['카카오 70% 이상으로', '단 게 당길 때 두 조각만'],
      pairsWith: ['almonds', 'milk', 'blueberry'],
    ),
    FoodItem(
      id: 'pumpkin_seed',
      name: '호박씨',
      category: NutrientCategory.fat,
      serving: '1큰술 10g',
      kcal: 56,
      protein: 3,
      carbs: 1,
      fat: 5,
      tags: {_n, _p},
      howToEat: ['샐러드·요거트에 뿌려서', '무염 제품을 고르세요'],
      pairsWith: ['salad_pack', 'greek_yogurt', 'oatmeal'],
    ),
    FoodItem(
      id: 'hummus',
      name: '후무스',
      category: NutrientCategory.fat,
      serving: '2큰술 30g',
      kcal: 75,
      protein: 2,
      carbs: 4,
      fat: 5.5,
      tags: {_n, _p},
      howToEat: ['채소 스틱을 찍어 먹어요', '빵에 발라도 좋아요'],
      pairsWith: ['carrot', 'cucumber', 'whole_wheat_bread'],
    ),

    // ── 채소 · 과일 ──
    FoodItem(
      id: 'broccoli',
      name: '브로콜리',
      category: NutrientCategory.vegFruit,
      serving: '1컵 80g',
      kcal: 27,
      protein: 2.3,
      carbs: 5.3,
      fat: 0.3,
      tags: {_p},
      howToEat: ['1–2분만 데쳐서', '냉동 브로콜리도 괜찮아요'],
      pairsWith: ['chicken_breast', 'shrimp', 'brown_rice'],
    ),
    FoodItem(
      id: 'spinach',
      name: '시금치 나물',
      category: NutrientCategory.vegFruit,
      serving: '1접시 70g',
      kcal: 30,
      protein: 2,
      carbs: 3,
      fat: 1.5,
      tags: {_p},
      howToEat: ['데쳐서 참기름 조금으로', '반찬으로 매 끼니 곁들이세요'],
      pairsWith: ['brown_rice', 'mackerel', 'tofu'],
    ),
    FoodItem(
      id: 'cherry_tomato',
      name: '방울토마토',
      category: NutrientCategory.vegFruit,
      serving: '10개 150g',
      kcal: 27,
      protein: 1.4,
      carbs: 6,
      fat: 0.3,
      tags: {_c, _n, _p},
      howToEat: ['씻어서 바로', '간식이나 야식 대신'],
      pairsWith: ['egg', 'cheese', 'greek_yogurt'],
    ),
    FoodItem(
      id: 'blueberry',
      name: '블루베리',
      category: NutrientCategory.vegFruit,
      serving: '한 줌 70g',
      kcal: 40,
      protein: 0.5,
      carbs: 10,
      fat: 0.2,
      tags: {_n, _p},
      howToEat: ['요거트·오트밀에 올려서', '냉동 블루베리도 괜찮아요'],
      pairsWith: ['greek_yogurt', 'oatmeal', 'almonds'],
    ),
    FoodItem(
      id: 'apple',
      name: '사과',
      category: NutrientCategory.vegFruit,
      serving: '반 개 150g',
      kcal: 78,
      protein: 0.4,
      carbs: 21,
      fat: 0.3,
      tags: {_n, _p},
      howToEat: ['껍질째 먹으면 식이섬유가 더 많아요', '땅콩버터를 곁들이면 든든해요'],
      pairsWith: ['peanut_butter', 'almonds', 'greek_yogurt'],
    ),
    FoodItem(
      id: 'salad_pack',
      name: '샐러드',
      category: NutrientCategory.vegFruit,
      serving: '1팩 150g (드레싱 별도)',
      kcal: 40,
      protein: 2,
      carbs: 7,
      fat: 0.5,
      tags: {_c, _n, _p},
      howToEat: ['드레싱은 반만 넣으세요', '닭가슴살·계란을 더해 한 끼로'],
      pairsWith: ['chicken_breast', 'egg', 'tuna_can'],
    ),
    FoodItem(
      id: 'cabbage',
      name: '양배추',
      category: NutrientCategory.vegFruit,
      serving: '100g',
      kcal: 25,
      protein: 1.3,
      carbs: 5.8,
      fat: 0.1,
      tags: {_p},
      howToEat: ['쪄서 쌈으로', '속이 편해요'],
      pairsWith: ['pork_tenderloin', 'beef_round', 'mackerel'],
    ),
    FoodItem(
      id: 'kiwi',
      name: '키위',
      category: NutrientCategory.vegFruit,
      serving: '1개 90g',
      kcal: 55,
      protein: 1,
      carbs: 13,
      fat: 0.5,
      tags: {_n, _p},
      howToEat: ['반 갈라 숟가락으로', '비타민 C가 많아요'],
      pairsWith: ['greek_yogurt', 'oatmeal', 'almonds'],
    ),
    FoodItem(
      id: 'carrot',
      name: '당근',
      category: NutrientCategory.vegFruit,
      serving: '반 개 80g',
      kcal: 33,
      protein: 0.7,
      carbs: 7.7,
      fat: 0.2,
      tags: {_n, _p},
      howToEat: ['스틱으로 잘라 간식으로', '기름에 살짝 볶으면 흡수가 좋아요'],
      pairsWith: ['hummus', 'cucumber', 'egg'],
    ),
    FoodItem(
      id: 'mushroom',
      name: '버섯',
      category: NutrientCategory.vegFruit,
      serving: '100g',
      kcal: 25,
      protein: 3,
      carbs: 4,
      fat: 0.3,
      tags: {_p},
      howToEat: ['볶거나 구워서 고기와 함께', '찌개에 넣어도 좋아요'],
      pairsWith: ['beef_round', 'tofu', 'pork_tenderloin'],
    ),
    FoodItem(
      id: 'mandarin',
      name: '귤',
      category: NutrientCategory.vegFruit,
      serving: '2개 160g',
      kcal: 70,
      protein: 1,
      carbs: 18,
      fat: 0.2,
      tags: {_n, _p},
      howToEat: ['간식으로 두 개', '하얀 속껍질까지 드세요'],
      pairsWith: ['greek_yogurt', 'almonds', 'egg'],
    ),
    FoodItem(
      id: 'cucumber',
      name: '오이',
      category: NutrientCategory.vegFruit,
      serving: '1개 200g',
      kcal: 30,
      protein: 1.3,
      carbs: 7,
      fat: 0.2,
      tags: {_c, _n, _p},
      howToEat: ['야식이 당길 때 씹을거리로', '편의점 오이 스틱도 있어요'],
      pairsWith: ['hummus', 'tuna_can', 'egg'],
    ),
  ];

  static final Map<String, FoodItem> _byId = {for (final f in foods) f.id: f};

  static FoodItem? byId(String id) => _byId[id];

  static List<FoodItem> byCategory(NutrientCategory category) =>
      foods.where((f) => f.category == category).toList();

  /// 상황·짝 음식 목록의 id를 음식으로 바꾼다 (없는 id는 건너뛴다).
  static List<FoodItem> resolve(List<String> ids) => [
    for (final id in ids)
      if (_byId[id] case final food?) food,
  ];
}
